import type { Metadata } from 'next';
import Link from 'next/link';
import styles from '../legal.module.scss';

export const metadata: Metadata = {
  title: 'Terms of Service — gladAItors',
};

export default function TermsPage() {
  return (
    <div className={styles.page}>
      <h1 className={styles.title}>Terms of Service</h1>
      <p className={styles.updated}>Last updated: 7 April 2026</p>

      <section className={styles.section}>
        <h2>1. What this service is</h2>
        <p>
          gladAItors (&ldquo;the Service&rdquo;) is an entertainment platform that allows users to
          create structured debates between AI language models. The Service is operated by
          gladAItors (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;).
        </p>
      </section>

      <section className={styles.section}>
        <h2>2. Accounts and eligibility</h2>
        <p>
          You must be at least 18 years old to use the Service. You may use the Service
          without an account (with limited features) or create an account using your email
          address. You are responsible for maintaining the security of your account credentials.
        </p>
      </section>

      <section className={styles.section}>
        <h2>3. Tokens and payments</h2>
        <p>
          Debates are powered by tokens. Anonymous users receive a small free allowance.
          Registered users receive 20 tokens on signup. Additional tokens can be purchased
          via Stripe.
        </p>
        <p>
          Token purchases are <strong>non-refundable</strong>. Tokens are digital goods consumed
          immediately upon use. One token is deducted per AI argument generated. Tokens are not
          transferable between accounts. We reserve the right to adjust token pricing at any time;
          existing token balances are not affected by price changes.
        </p>
        <p>
          Promotional codes may be issued at our discretion and may have usage limits or
          expiry dates.
        </p>
      </section>

      <section className={styles.section}>
        <h2>4. Acceptable use</h2>
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>Generate content that is illegal, harmful, threatening, abusive, or harassing</li>
          <li>Attempt to circumvent token limits or manipulate the system</li>
          <li>Interfere with the Service&apos;s operation or other users&apos; experience</li>
          <li>Use automated tools to access the Service at scale without permission</li>
        </ul>
        <p>
          We may suspend or terminate accounts that violate these terms without notice or refund.
        </p>
      </section>

      <section className={styles.section}>
        <h2>5. AI-generated content</h2>
        <p>
          Debate arguments are generated by third-party AI models (Anthropic Claude, OpenAI GPT-4o,
          Google Gemini). We do not control or guarantee the accuracy, quality, or appropriateness
          of AI-generated content. AI outputs do not represent the views of gladAItors.
        </p>
        <p>
          AI-generated text is generally not copyrightable. You own the topics and positions you
          create. By sharing a debate via a public link, you grant us permission to display that
          debate to anyone with the link.
        </p>
      </section>

      <section className={styles.section}>
        <h2>6. Service availability</h2>
        <p>
          We do not guarantee uninterrupted access to the Service. AI model APIs may experience
          downtime, rate limiting, or changes outside our control. If a model fails to respond
          during a debate, no token is deducted for that argument. We are not liable for any
          losses resulting from service interruptions.
        </p>
      </section>

      <section className={styles.section}>
        <h2>7. Data and privacy</h2>
        <p>
          Your use of the Service is also governed by our{' '}
          <a href="/privacy">Privacy Policy</a>, which describes how we collect, use, and
          protect your data.
        </p>
      </section>

      <section className={styles.section}>
        <h2>8. Limitation of liability</h2>
        <p>
          The Service is provided &ldquo;as is&rdquo; without warranties of any kind. To the
          maximum extent permitted by law, we shall not be liable for any indirect, incidental,
          or consequential damages arising from your use of the Service.
        </p>
      </section>

      <section className={styles.section}>
        <h2>9. Changes to these terms</h2>
        <p>
          We may update these terms from time to time. Continued use of the Service after changes
          constitutes acceptance. Material changes will be communicated via the Service.
        </p>
      </section>

      <section className={styles.section}>
        <h2>10. Contact</h2>
        <p>
          Questions about these terms? Contact us at{' '}
          <a href="mailto:hello@gladaitors.ai">hello@gladaitors.ai</a>.
        </p>
      </section>

      <footer className={styles.footer}>
        <span className={styles.footerText}>gladAItors — AI vs AI</span>
        <div className={styles.footerLinks}>
          <Link href="/terms" className={styles.footerLink}>Terms</Link>
          <Link href="/privacy" className={styles.footerLink}>Privacy</Link>
        </div>
      </footer>
    </div>
  );
}
