// ============================================================================
// Model registry — single source of truth for AI debater models
// ============================================================================
// Adding a new model: add an entry here. Updating a model version: change
// `providerModelId` here. Both work everywhere automatically — the API,
// the form picker, the debate display, the share modal, and the homepage.
// ============================================================================

export type ModelFamily = 'claude' | 'gpt' | 'gemini' | 'user';

export interface ModelDefinition {
  /** The variant id sent over the wire and stored in the database */
  id: string;
  /** The model family — drives colour and which streamer/provider to call */
  family: ModelFamily;
  /** Display name shown in UI */
  name: string;
  /** Version label shown next to the name (e.g. "4.6", "2.5") */
  version: string;
  /** Tier label shown in UI */
  tier: 'standard' | 'premium';
  /** Tokens deducted per argument generated by this model */
  tokenCost: number;
  /** The exact API model identifier sent to the provider's SDK */
  providerModelId: string;
}

const FAMILY_COLOURS: Record<ModelFamily, string> = {
  claude: '#D97757',  // Anthropic orange
  gpt:    '#10A37F',  // ChatGPT teal
  gemini: '#4285F4',  // Google blue
  user:   '#FFD700',  // gold — the human player
};

export const MODELS: ModelDefinition[] = [
  // --- Claude ---
  {
    id: 'claude-sonnet',
    family: 'claude',
    name: 'Claude Sonnet',
    version: '4.6',
    tier: 'standard',
    tokenCost: 1,
    providerModelId: 'claude-sonnet-4-6',
  },
  {
    id: 'claude-opus',
    family: 'claude',
    name: 'Claude Opus',
    version: '4.6',
    tier: 'premium',
    tokenCost: 4,
    providerModelId: 'claude-opus-4-6',
  },

  // --- GPT ---
  {
    id: 'gpt-4o',
    family: 'gpt',
    name: 'GPT-4o',
    version: '',
    tier: 'standard',
    tokenCost: 1,
    providerModelId: 'gpt-4o',
  },
  {
    id: 'gpt-5',
    family: 'gpt',
    name: 'GPT-5',
    version: '',
    tier: 'premium',
    tokenCost: 3,
    providerModelId: 'gpt-5',
  },

  // --- Gemini ---
  {
    id: 'gemini-flash',
    family: 'gemini',
    name: 'Gemini Flash',
    version: '2.5',
    tier: 'standard',
    tokenCost: 1,
    providerModelId: 'gemini-2.5-flash',
  },
  {
    id: 'gemini-pro',
    family: 'gemini',
    name: 'Gemini Pro',
    version: '2.5',
    tier: 'premium',
    tokenCost: 3,
    providerModelId: 'gemini-2.5-pro',
  },

  // --- Human player ---
  // Token cost is 0 — the user isn't consuming an AI call.
  // providerModelId is empty because there's no provider; the API skips this slot.
  // Picker label and rendered display name both use "Human" (with " 1" / " 2"
  // suffixes for duplicates) so the model picker and the debate thread agree.
  {
    id: 'user',
    family: 'user',
    name: 'Human',
    version: '',
    tier: 'standard',
    tokenCost: 0,
    providerModelId: '',
  },
];

const MODEL_BY_ID = Object.fromEntries(MODELS.map(m => [m.id, m]));

/** Look up a model by its variant id. Throws if unknown. */
export function getModel(id: string): ModelDefinition {
  const model = MODEL_BY_ID[id];
  if (!model) throw new Error(`Unknown model: ${id}`);
  return model;
}

/** Safe lookup that returns undefined for unknown ids. */
export function findModel(id: string): ModelDefinition | undefined {
  return MODEL_BY_ID[id];
}

/** Get the brand colour for a model id, defaulting to grey if unknown. */
export function getModelColour(id: string): string {
  const model = MODEL_BY_ID[id];
  return model ? FAMILY_COLOURS[model.family] : '#888';
}

/** Get the display name for a model id, defaulting to the id itself. */
export function getModelName(id: string): string {
  return MODEL_BY_ID[id]?.name || id;
}

/** Get the token cost for a model id. Defaults to 1. */
export function getModelTokenCost(id: string): number {
  return MODEL_BY_ID[id]?.tokenCost ?? 1;
}
